version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd cra-website && npm install
  build:
    commands:
      - npm run build

artifacts:
  base-directory: ./cra-website/build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'